import './admin-user';
import './profile-edit-profile';
import './profile-edit-password';
import './aluno';
import './curso';
import './turma';
import './disciplina';
import './aluno-turma';
import './publicacao';
